Exercise.find_or_create(name: "Bench Press", increment: 2.5)
Exercise.find_or_create(name: "OHP", increment: 2.5)
Exercise.find_or_create(name: "Row", increment: 2.5)
Exercise.find_or_create(name: "Chin Up", increment: 0.0)
Exercise.find_or_create(name: "Squat", increment: 2.5)
Exercise.find_or_create(name: "Deadlift", increment: 5.0)
Exercise.find_or_create(name: "Tricep Ext", increment: 0.0)
Exercise.find_or_create(name: "Bicep Curl", increment: 0.0)
Exercise.find_or_create(name: "Ab Rollout", increment: 0.0)
Exercise.find_or_create(name: "Shrug", increment: 0.0)
